import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import ItemStats from "@/components/items/ItemStats";
import ItemForm from "@/components/items/ItemForm";
import ItemsHeader from "@/components/items/ItemsHeader";
import ItemsControls from "@/components/items/ItemsControls";
import ItemsDisplay from "@/components/items/ItemsDisplay";

interface Item {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
  isAvailable: boolean;
  stockCount: number;
  lowStockAlert: number;
  allergens: string[];
  modifiers: string[];
  preparationTime: number;
  calories: number;
  isVegetarian: boolean;
  isVegan: boolean;
  isGlutenFree: boolean;
  createdAt: string;
  updatedAt: string;
}

const initialItems: Item[] = [
  // HOT STARTERS - SOUPS
  {
    id: '1',
    name: 'Vegetables Clear Soup',
    description: 'Fresh vegetables in clear broth',
    price: 15.00,
    category: 'Hot Starters',
    image: '/lovable-uploads/19d37793-8356-4039-8e0e-2c4ab8fb2710.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Vegetables', 'Spicy'],
    preparationTime: 10,
    calories: 85,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20'
  },
  {
    id: '2',
    name: 'Vegetables Cream Soup',
    description: 'Creamy vegetable soup with herbs',
    price: 20.00,
    category: 'Hot Starters',
    image: '/lovable-uploads/19d37793-8356-4039-8e0e-2c4ab8fb2710.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 3,
    allergens: ['Dairy'],
    modifiers: ['Extra Cream', 'Herbs'],
    preparationTime: 12,
    calories: 180,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-16',
    updatedAt: '2024-01-18'
  },
  {
    id: '3',
    name: 'Chicken Minestrone Soup',
    description: 'Hearty Italian soup with chicken and vegetables',
    price: 20.00,
    category: 'Hot Starters',
    image: '/lovable-uploads/19d37793-8356-4039-8e0e-2c4ab8fb2710.png',
    isAvailable: true,
    stockCount: 15,
    lowStockAlert: 3,
    allergens: ['Gluten'],
    modifiers: ['Extra Chicken', 'Spicy'],
    preparationTime: 15,
    calories: 220,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-01-17',
    updatedAt: '2024-01-19'
  },
  // MAIN COURSE - VEGETARIAN
  {
    id: '4',
    name: 'Taawa Mushroom',
    description: 'Mixed berry peppers, whole Mushroom Cashew nuts, finished in cream, Sauce and Indian Spices - Served with Rice',
    price: 30.00,
    category: 'Main Course',
    image: '/lovable-uploads/19d37793-8356-4039-8e0e-2c4ab8fb2710.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: ['Dairy', 'Nuts'],
    modifiers: ['Extra Mushrooms', 'Spicy', 'No Nuts'],
    preparationTime: 20,
    calories: 380,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-21'
  },
  {
    id: '5',
    name: 'Vegetables BBQ Balls',
    description: 'Seasoned mixed Vegetables, mixed with Aromatic Spices, Finished in BBQ Sauce, served with Rice and Chapati',
    price: 30.00,
    category: 'Main Course',
    image: '/lovable-uploads/19d37793-8356-4039-8e0e-2c4ab8fb2710.png',
    isAvailable: true,
    stockCount: 22,
    lowStockAlert: 5,
    allergens: ['Gluten'],
    modifiers: ['Extra BBQ Sauce', 'No Chapati'],
    preparationTime: 18,
    calories: 420,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    createdAt: '2024-01-19',
    updatedAt: '2024-01-22'
  },
  // PIZZA CORNER
  {
    id: '6',
    name: 'Margherita Pizza',
    description: 'Tomato concasse, mozzarella cheese and oregano',
    price: 30.00,
    category: 'Pizza',
    image: '/lovable-uploads/d6676517-8dfb-4b06-8137-c48dd353c02d.png',
    isAvailable: true,
    stockCount: 15,
    lowStockAlert: 3,
    allergens: ['Gluten', 'Dairy'],
    modifiers: ['Large Size', 'Extra Cheese', 'Thin Crust'],
    preparationTime: 15,
    calories: 580,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-01-20',
    updatedAt: '2024-01-23'
  },
  {
    id: '7',
    name: 'Metric Chello Pizza Large',
    description: 'A Grilled combo meat, beef, chicken, sausages, and vegetables, cheese, Oregano',
    price: 40.00,
    category: 'Pizza',
    image: '/lovable-uploads/d6676517-8dfb-4b06-8137-c48dd353c02d.png',
    isAvailable: true,
    stockCount: 10,
    lowStockAlert: 2,
    allergens: ['Gluten', 'Dairy'],
    modifiers: ['Medium Size', 'Extra Meat', 'Spicy'],
    preparationTime: 20,
    calories: 750,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-01-21',
    updatedAt: '2024-01-24'
  },
  // MAIN COURSE - CHICKEN
  {
    id: '8',
    name: 'Oven Grilled Chicken',
    description: 'A Choice of Chicken part on bone either the Thigh or breast marinaded in a mild spices and oven Grilled to perfection',
    price: 36.00,
    category: 'Chicken',
    image: '/lovable-uploads/d6676517-8dfb-4b06-8137-c48dd353c02d.png',
    isAvailable: true,
    stockCount: 12,
    lowStockAlert: 3,
    allergens: [],
    modifiers: ['Thigh', 'Breast', 'Extra Spicy'],
    preparationTime: 25,
    calories: 480,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-22',
    updatedAt: '2024-01-25'
  },
  {
    id: '9',
    name: 'Metric Whole Chicken',
    description: 'A choice of Grilled or fried whole chicken marinaded in mild spices served with brown rice and chips',
    price: 80.00,
    category: 'Chicken',
    image: '/lovable-uploads/d6676517-8dfb-4b06-8137-c48dd353c02d.png',
    isAvailable: true,
    stockCount: 8,
    lowStockAlert: 2,
    allergens: [],
    modifiers: ['Grilled', 'Fried', 'Extra Rice'],
    preparationTime: 35,
    calories: 1200,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-23',
    updatedAt: '2024-01-26'
  },
  // BEEF TOLL
  {
    id: '10',
    name: 'Grilled Beef Steak',
    description: 'A tender beef fillet marinated with soy sauce, garlic, peppers served with mushroom sauce, Chips or rice',
    price: 30.00,
    category: 'Beef',
    image: '/lovable-uploads/78cd53f6-59c5-4e65-b665-25dd36239651.png',
    isAvailable: true,
    stockCount: 14,
    lowStockAlert: 3,
    allergens: ['Soy'],
    modifiers: ['Medium Rare', 'Well Done', 'Extra Sauce'],
    preparationTime: 22,
    calories: 520,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-24',
    updatedAt: '2024-01-27'
  },
  {
    id: '11',
    name: 'Beef Muchomo',
    description: 'Boneless tender beef cubes roasted with onions and skewered with tomatoes green berry paper served with banana fingers or chips',
    price: 29.00,
    category: 'Beef',
    image: '/lovable-uploads/78cd53f6-59c5-4e65-b665-25dd36239651.png',
    isAvailable: true,
    stockCount: 16,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Banana Fingers', 'Chips', 'Extra Spicy'],
    preparationTime: 20,
    calories: 450,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-25',
    updatedAt: '2024-01-28'
  },
  // FISH ROUND
  {
    id: '12',
    name: 'Grilled Fish Fillet',
    description: 'Garlic butter Marinated fish fillet grilled with paprika sauce, served with tartar sauce accompanied by rice, wedges',
    price: 35.00,
    category: 'Fish',
    image: '/lovable-uploads/78cd53f6-59c5-4e65-b665-25dd36239651.png',
    isAvailable: true,
    stockCount: 10,
    lowStockAlert: 2,
    allergens: ['Fish', 'Dairy'],
    modifiers: ['Extra Tartar Sauce', 'Lemon', 'Spicy'],
    preparationTime: 18,
    calories: 380,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-26',
    updatedAt: '2024-01-29'
  },
  {
    id: '13',
    name: 'Metric Fried Whole Fish',
    description: 'A lake Victoria Whole fish seasoned with lemon juice and deep fried, served with topped vegetables, chips or wedges',
    price: 49.00,
    category: 'Fish',
    image: '/lovable-uploads/78cd53f6-59c5-4e65-b665-25dd36239651.png',
    isAvailable: true,
    stockCount: 6,
    lowStockAlert: 1,
    allergens: ['Fish'],
    modifiers: ['Chips', 'Wedges', 'Extra Vegetables'],
    preparationTime: 25,
    calories: 650,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-27',
    updatedAt: '2024-01-30'
  },
  // INDIAN CORNER
  {
    id: '14',
    name: 'Chicken Tikka Masala',
    description: 'Boneless chicken cubes marinated in Indian home made spices and cooked with tomato gravy Served with Chapati or rice',
    price: 35.00,
    category: 'Indian',
    image: '/lovable-uploads/d2fddca9-8a5a-48c2-b950-2aa02db1232a.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: ['Dairy', 'Gluten'],
    modifiers: ['Chapati', 'Rice', 'Extra Spicy'],
    preparationTime: 22,
    calories: 480,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-01-28',
    updatedAt: '2024-01-31'
  },
  {
    id: '15',
    name: 'Butter Chicken',
    description: 'Spiced Chicken cubes marinated overnight and cooked in mild butter sauce served with rice',
    price: 37.00,
    category: 'Indian',
    image: '/lovable-uploads/d2fddca9-8a5a-48c2-b950-2aa02db1232a.png',
    isAvailable: true,
    stockCount: 15,
    lowStockAlert: 3,
    allergens: ['Dairy'],
    modifiers: ['Extra Butter', 'Mild', 'Medium Spicy'],
    preparationTime: 25,
    calories: 550,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-29',
    updatedAt: '2024-02-01'
  },
  // GOAT
  {
    id: '16',
    name: 'Pan Fried Goat',
    description: 'Tender pieces of goats meat pan fried with all berry pepper in a think gravy, served with chips / rice',
    price: 38.00,
    category: 'Goat',
    image: '/lovable-uploads/d2fddca9-8a5a-48c2-b950-2aa02db1232a.png',
    isAvailable: true,
    stockCount: 12,
    lowStockAlert: 3,
    allergens: [],
    modifiers: ['Chips', 'Rice', 'Extra Gravy'],
    preparationTime: 30,
    calories: 580,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-30',
    updatedAt: '2024-02-02'
  },
  {
    id: '17',
    name: 'Goat Muchomo Per Kg',
    description: 'ROASTED NYAMA CHOMA with Kachumbari. Served with baked matooke or Roasted potatoes',
    price: 60.00,
    category: 'Goat',
    image: '/lovable-uploads/d2fddca9-8a5a-48c2-b950-2aa02db1232a.png',
    isAvailable: true,
    stockCount: 8,
    lowStockAlert: 2,
    allergens: [],
    modifiers: ['Baked Matooke', 'Roasted Potatoes', 'Extra Kachumbari'],
    preparationTime: 40,
    calories: 720,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-01-31',
    updatedAt: '2024-02-03'
  },
  // BURGERS
  {
    id: '18',
    name: 'Grilled Chicken Burger',
    description: 'Overnight marinated chicken breast sandwiched between a soft burger bun with fresh layers of vegetables and cheddar cheese, served with chips',
    price: 32.00,
    category: 'Burgers',
    image: '/lovable-uploads/ccd29f06-723a-44f2-972d-7bb895cf8a9e.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 5,
    allergens: ['Gluten', 'Dairy'],
    modifiers: ['No Cheese', 'Extra Vegetables', 'Spicy'],
    preparationTime: 15,
    calories: 650,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-02-01',
    updatedAt: '2024-02-04'
  },
  {
    id: '19',
    name: 'Metric Heavy Burger',
    description: 'Two meat parties with a choice of Beef or Chicken, sandwiched with creamy mushroom and fried eggs, served with chips',
    price: 35.00,
    category: 'Burgers',
    image: '/lovable-uploads/ccd29f06-723a-44f2-972d-7bb895cf8a9e.png',
    isAvailable: true,
    stockCount: 15,
    lowStockAlert: 3,
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    modifiers: ['Beef', 'Chicken', 'No Mushroom'],
    preparationTime: 18,
    calories: 850,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-02-02',
    updatedAt: '2024-02-05'
  },
  // SPAGHETTI
  {
    id: '20',
    name: 'Spaghetti Bolognaise',
    description: 'Italian spaghetti smoothened in savory and flavor full minced meat, topped with cheese',
    price: 30.00,
    category: 'Pasta',
    image: '/lovable-uploads/f71433c6-1ae3-42c4-b356-4cb6be6ed173.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Gluten', 'Dairy'],
    modifiers: ['Extra Cheese', 'Extra Meat', 'Vegetarian'],
    preparationTime: 20,
    calories: 680,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-02-03',
    updatedAt: '2024-02-06'
  },
  // DESSERTS
  {
    id: '21',
    name: 'Fruit Sundae',
    description: 'American dessert with mixed fruits topped with a scoop of a cream, and chocolate syrup',
    price: 20.00,
    category: 'Desserts',
    image: '/lovable-uploads/f71433c6-1ae3-42c4-b356-4cb6be6ed173.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Extra Cream', 'No Chocolate', 'Extra Fruits'],
    preparationTime: 8,
    calories: 320,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-04',
    updatedAt: '2024-02-07'
  },
  {
    id: '22',
    name: 'Banana Split',
    description: 'Caramelised banana served with ice cream and a chocolate syrup',
    price: 18.00,
    category: 'Desserts',
    image: '/lovable-uploads/f71433c6-1ae3-42c4-b356-4cb6be6ed173.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 6,
    allergens: ['Dairy'],
    modifiers: ['Extra Ice Cream', 'No Chocolate', 'Vanilla'],
    preparationTime: 10,
    calories: 380,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-05',
    updatedAt: '2024-02-08'
  },
  // COFFEE & ESPRESSO-BASED DRINKS
  {
    id: '23',
    name: 'Espresso',
    description: 'Strong concentrated shot of coffee made with high quality African coffee beans',
    price: 8.00,
    category: 'Coffee',
    image: '/lovable-uploads/0ef70ac7-d461-4233-b638-0ef310993bba.png',
    isAvailable: true,
    stockCount: 50,
    lowStockAlert: 10,
    allergens: [],
    modifiers: ['Double Shot', 'Decaf'],
    preparationTime: 3,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-02-06',
    updatedAt: '2024-02-09'
  },
  {
    id: '24',
    name: 'African Coffee',
    description: 'Espresso-based coffee with our freshly steamed hot milk',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/0ef70ac7-d461-4233-b638-0ef310993bba.png',
    isAvailable: true,
    stockCount: 45,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Oat Milk', 'Almond Milk', 'Extra Shot'],
    preparationTime: 5,
    calories: 120,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-07',
    updatedAt: '2024-02-10'
  },
  {
    id: '25',
    name: 'Black Coffee',
    description: 'Bold, straight forward with pure taste',
    price: 7.00,
    category: 'Coffee',
    image: '/lovable-uploads/0ef70ac7-d461-4233-b638-0ef310993bba.png',
    isAvailable: true,
    stockCount: 50,
    lowStockAlert: 10,
    allergens: [],
    modifiers: ['Sugar', 'Honey'],
    preparationTime: 3,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-02-08',
    updatedAt: '2024-02-11'
  },
  {
    id: '26',
    name: 'Americano',
    description: 'Espresso diluted with hot water, providing a milder flavor and smooth finish',
    price: 8.00,
    category: 'Coffee',
    image: '/lovable-uploads/0ef70ac7-d461-4233-b638-0ef310993bba.png',
    isAvailable: true,
    stockCount: 45,
    lowStockAlert: 8,
    allergens: [],
    modifiers: ['Extra Shot', 'Iced'],
    preparationTime: 4,
    calories: 10,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-02-09',
    updatedAt: '2024-02-12'
  },
  {
    id: '27',
    name: 'Cappuccino',
    description: 'Rich espresso, velvety steamed milk and layer of cream come together in perfect harmony',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Oat Milk', 'Almond Milk', 'Extra Foam'],
    preparationTime: 6,
    calories: 150,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-10',
    updatedAt: '2024-02-13'
  },
  {
    id: '28',
    name: 'Metric Latte',
    description: 'Our expertly crafted rich African espresso and steamed milk combined in a delight and balanced cup',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Oat Milk', 'Vanilla', 'Caramel'],
    preparationTime: 6,
    calories: 190,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-11',
    updatedAt: '2024-02-14'
  },
  {
    id: '29',
    name: 'Metric Mochachino',
    description: 'Decadent blend of espresso, chocolate syrup and steamed milk',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: ['Dairy'],
    modifiers: ['Extra Chocolate', 'Whipped Cream'],
    preparationTime: 7,
    calories: 250,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-12',
    updatedAt: '2024-02-15'
  },
  {
    id: '30',
    name: 'Metric Macchiato',
    description: 'A delicate balance of espresso "marked" with a touch of frothed milk',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Caramel', 'Vanilla'],
    preparationTime: 5,
    calories: 80,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-13',
    updatedAt: '2024-02-16'
  },
  {
    id: '31',
    name: 'Irish Coffee',
    description: 'Irish whisky added to our freshly extracted espresso for your perfect strong taste',
    price: 15.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy', 'Alcohol'],
    modifiers: ['Extra Whisky', 'Whipped Cream'],
    preparationTime: 8,
    calories: 320,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-14',
    updatedAt: '2024-02-17'
  },
  {
    id: '32',
    name: 'Caramel Latte',
    description: 'Espresso caramel syrup with steamed milk foam',
    price: 12.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: ['Dairy'],
    modifiers: ['Extra Caramel', 'Oat Milk'],
    preparationTime: 6,
    calories: 280,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-15',
    updatedAt: '2024-02-18'
  },
  {
    id: '33',
    name: 'Vanilla Latte',
    description: 'Espresso vanilla syrup with steamed milk foam',
    price: 12.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: ['Dairy'],
    modifiers: ['Extra Vanilla', 'Almond Milk'],
    preparationTime: 6,
    calories: 260,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-16',
    updatedAt: '2024-02-19'
  },
  {
    id: '34',
    name: 'Hazelnut Latte',
    description: 'Espresso hazelnut with steamed milk foam',
    price: 12.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: ['Dairy', 'Nuts'],
    modifiers: ['Extra Hazelnut', 'No Nuts'],
    preparationTime: 6,
    calories: 270,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-17',
    updatedAt: '2024-02-20'
  },
  {
    id: '35',
    name: 'Cinnamon Latte',
    description: 'Espresso cinnamon with steamed milk foam',
    price: 12.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: ['Dairy'],
    modifiers: ['Extra Cinnamon', 'Honey'],
    preparationTime: 6,
    calories: 250,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-18',
    updatedAt: '2024-02-21'
  },
  {
    id: '36',
    name: 'Latte Macchiato',
    description: 'Espresso with steamed milk foam',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Extra Foam', 'Oat Milk'],
    preparationTime: 6,
    calories: 180,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-19',
    updatedAt: '2024-02-22'
  },
  {
    id: '37',
    name: 'Decaffeinated Coffee',
    description: 'Swiss water process, decaf coffee beans ensuring rich taste without caffeine (caffeine-free)',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/0ef70ac7-d461-4233-b638-0ef310993bba.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Milk', 'Sugar'],
    preparationTime: 5,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-02-20',
    updatedAt: '2024-02-23'
  },
  {
    id: '38',
    name: 'Affogato',
    description: 'Vanilla ice cream meets rich espresso and steamed milk in this indulgent treat',
    price: 18.00,
    category: 'Coffee',
    image: '/lovable-uploads/789041ef-2565-4d45-80ea-d854c800cbc6.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Extra Ice Cream', 'Chocolate Syrup'],
    preparationTime: 5,
    calories: 280,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-21',
    updatedAt: '2024-02-24'
  },
  {
    id: '39',
    name: 'Romano',
    description: 'Espresso fresh lemon juice steamed together',
    price: 10.00,
    category: 'Coffee',
    image: '/lovable-uploads/0ef70ac7-d461-4233-b638-0ef310993bba.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: [],
    modifiers: ['Extra Lemon', 'Sugar'],
    preparationTime: 4,
    calories: 15,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-02-22',
    updatedAt: '2024-02-25'
  },
  {
    id: '40',
    name: 'Metric Frappes',
    description: 'Cold blended coffee drinks in various flavors of your choice',
    price: 15.00,
    category: 'Coffee',
    image: '/lovable-uploads/0ef70ac7-d461-4233-b638-0ef310993bba.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: ['Dairy'],
    modifiers: ['Vanilla', 'Caramel', 'Mocha'],
    preparationTime: 8,
    calories: 350,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-23',
    updatedAt: '2024-02-26'
  },
  // ICED COFFEE
  {
    id: '41',
    name: 'Iced Cappuccino',
    description: 'Rich espresso with cold milk and ice',
    price: 10.00,
    category: 'Iced Coffee',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Oat Milk', 'Extra Ice'],
    preparationTime: 5,
    calories: 120,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-24',
    updatedAt: '2024-02-27'
  },
  {
    id: '42',
    name: 'Iced Mocha',
    description: 'Cold espresso with chocolate and milk over ice',
    price: 10.00,
    category: 'Iced Coffee',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: ['Dairy'],
    modifiers: ['Whipped Cream', 'Extra Chocolate'],
    preparationTime: 6,
    calories: 220,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-25',
    updatedAt: '2024-02-28'
  },
  {
    id: '43',
    name: 'Iced Latte',
    description: 'Smooth espresso with cold milk over ice',
    price: 10.00,
    category: 'Iced Coffee',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Almond Milk', 'Vanilla'],
    preparationTime: 5,
    calories: 160,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-26',
    updatedAt: '2024-03-01'
  },
  {
    id: '44',
    name: 'Iced Chocolate',
    description: 'Rich chocolate drink served cold over ice',
    price: 10.00,
    category: 'Iced Coffee',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: ['Dairy'],
    modifiers: ['Whipped Cream', 'Mint'],
    preparationTime: 5,
    calories: 250,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-02-27',
    updatedAt: '2024-03-02'
  },
  {
    id: '45',
    name: 'Iced Espresso',
    description: 'Strong espresso served over ice',
    price: 10.00,
    category: 'Iced Coffee',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 45,
    lowStockAlert: 9,
    allergens: [],
    modifiers: ['Sugar', 'Lemon'],
    preparationTime: 3,
    calories: 10,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-02-28',
    updatedAt: '2024-03-03'
  },
  // CHOCOLATE INDULGENCES
  {
    id: '46',
    name: 'Hot Chocolate',
    description: 'A rich, creamy hot chocolate made with dark African cocoa and hot milk',
    price: 10.00,
    category: 'Chocolate',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: ['Dairy'],
    modifiers: ['Whipped Cream', 'Marshmallows'],
    preparationTime: 5,
    calories: 280,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-04'
  },
  {
    id: '47',
    name: 'Dark Chocolate',
    description: 'Rich, intense with dark chocolate syrup',
    price: 10.00,
    category: 'Chocolate',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Dark', 'Whipped Cream'],
    preparationTime: 5,
    calories: 320,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-02',
    updatedAt: '2024-03-05'
  },
  // CLASSIC TEA
  {
    id: '48',
    name: 'African Tea',
    description: 'Indulge in the rich flavors of our signature blend combining African tea and subtle spices',
    price: 8.00,
    category: 'Tea',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: [],
    modifiers: ['Milk', 'Sugar', 'Lemon'],
    preparationTime: 5,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-03',
    updatedAt: '2024-03-06'
  },
  {
    id: '49',
    name: 'Black Tea',
    description: 'Classic and robust: Our black tea is sourced from the finest African tea estates',
    price: 5.00,
    category: 'Tea',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 50,
    lowStockAlert: 10,
    allergens: [],
    modifiers: ['Honey', 'Lemon', 'Milk'],
    preparationTime: 4,
    calories: 2,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-04',
    updatedAt: '2024-03-07'
  },
  {
    id: '50',
    name: 'Plain Milk',
    description: 'A choice of fresh hot plain milk or cold milk',
    price: 8.00,
    category: 'Tea',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 45,
    lowStockAlert: 9,
    allergens: ['Dairy'],
    modifiers: ['Hot', 'Cold', 'Honey'],
    preparationTime: 3,
    calories: 150,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-05',
    updatedAt: '2024-03-08'
  },
  {
    id: '51',
    name: 'English Tea',
    description: 'Hot water, tea leaves and hot milk aside',
    price: 10.00,
    category: 'Tea',
    image: '/lovable-uploads/1dc4cac3-8b60-4f55-a97a-e634bbde5f00.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Sugar', 'Lemon'],
    preparationTime: 5,
    calories: 50,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-06',
    updatedAt: '2024-03-09'
  },
  // ORGANIC CHAI
  {
    id: '52',
    name: 'Hibiscus Tea',
    description: 'Brewed hibiscus with hot water',
    price: 10.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Honey', 'Lemon'],
    preparationTime: 6,
    calories: 15,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-07',
    updatedAt: '2024-03-10'
  },
  {
    id: '53',
    name: 'Lemon Tea',
    description: 'Revitalize with our zesty lemon-infused black tea perfect for a refreshing pick-me-up',
    price: 10.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: [],
    modifiers: ['Extra Lemon', 'Honey'],
    preparationTime: 5,
    calories: 20,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-08',
    updatedAt: '2024-03-11'
  },
  {
    id: '54',
    name: 'White Ginger Tea (Mulondo)',
    description: 'Delicate and soothing, white ginger tea aid digestion and calms the senses',
    price: 10.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Honey', 'Lemon'],
    preparationTime: 7,
    calories: 10,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-09',
    updatedAt: '2024-03-12'
  },
  {
    id: '55',
    name: 'Pure Peppermint',
    description: 'Cool down with invigorating pure peppermint leaves, naturally caffeine-free',
    price: 10.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Honey', 'Extra Mint'],
    preparationTime: 5,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-13'
  },
  {
    id: '56',
    name: 'Pure Camomile',
    description: 'Unwind with the calming effects of pure camomile, herbal haven for relaxation',
    price: 10.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Honey', 'Lemon'],
    preparationTime: 6,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-11',
    updatedAt: '2024-03-14'
  },
  {
    id: '57',
    name: 'Dawa Tea',
    description: 'A soothing mix of herbs and spices including, lemon, garlic, cinnamon and honey, carefully crafted to uplift and revitalize',
    price: 12.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Honey', 'Extra Lemon'],
    preparationTime: 8,
    calories: 45,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-12',
    updatedAt: '2024-03-15'
  },
  {
    id: '58',
    name: 'Green Tea',
    description: 'A light, refreshing pure and simple, our green tea offers a delicate taste and numerous health benefits',
    price: 10.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: [],
    modifiers: ['Lemon', 'Honey'],
    preparationTime: 5,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-13',
    updatedAt: '2024-03-16'
  },
  {
    id: '59',
    name: 'Earl Gray Tea',
    description: 'A classic black tea infused with bergamot oil providing a subtle citrus flavor and sophisticated twist on traditional tea creating a refined and soothing cup',
    price: 10.00,
    category: 'Organic Chai',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Milk', 'Lemon'],
    preparationTime: 5,
    calories: 5,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-14',
    updatedAt: '2024-03-17'
  },
  // FLAVORED TEA
  {
    id: '60',
    name: 'Metric Orange Iced Tea',
    description: 'Vibrant orange zest infused into our soothing black tea proving a citrusy twist on classic',
    price: 15.00,
    category: 'Flavored Tea',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Orange', 'Mint'],
    preparationTime: 6,
    calories: 35,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-15',
    updatedAt: '2024-03-18'
  },
  {
    id: '61',
    name: 'Metric Raspberry Iced Tea',
    description: 'Tart raspberry flavors mixed with our zesty herbal tea making a sweet and revitalizing treat',
    price: 15.00,
    category: 'Flavored Tea',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Raspberry', 'Mint'],
    preparationTime: 6,
    calories: 40,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-16',
    updatedAt: '2024-03-19'
  },
  {
    id: '62',
    name: 'Metric Peach Iced Tea',
    description: 'Ripe peach flavors blended with our smooth black tea creating a fruity and refreshing summer drink',
    price: 15.00,
    category: 'Flavored Tea',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Peach', 'Mint'],
    preparationTime: 6,
    calories: 45,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-17',
    updatedAt: '2024-03-20'
  },
  {
    id: '63',
    name: 'Metric Passion Iced Tea',
    description: 'Sweety and tangy passion fruit infused into our refreshing green tea, perfect for warm days',
    price: 15.00,
    category: 'Flavored Tea',
    image: '/lovable-uploads/3012d302-6ecc-4bc3-a11c-aec2b88309f0.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Passion', 'Mint'],
    preparationTime: 6,
    calories: 40,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-18',
    updatedAt: '2024-03-21'
  },
  // MILKSHAKES
  {
    id: '64',
    name: 'Banana Shake',
    description: 'Creamy banana milkshake',
    price: 15.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: ['Dairy'],
    modifiers: ['Extra Banana', 'Honey'],
    preparationTime: 5,
    calories: 320,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-19',
    updatedAt: '2024-03-22'
  },
  {
    id: '65',
    name: 'Vanilla Shake',
    description: 'Classic vanilla milkshake',
    price: 15.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: ['Dairy'],
    modifiers: ['Extra Vanilla', 'Whipped Cream'],
    preparationTime: 5,
    calories: 300,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-20',
    updatedAt: '2024-03-23'
  },
  {
    id: '66',
    name: 'Strawberry Shake',
    description: 'Fresh strawberry milkshake',
    price: 15.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Strawberry', 'Whipped Cream'],
    preparationTime: 5,
    calories: 310,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-21',
    updatedAt: '2024-03-24'
  },
  {
    id: '67',
    name: 'Chocolate Shake',
    description: 'Rich chocolate milkshake',
    price: 15.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Chocolate', 'Whipped Cream'],
    preparationTime: 5,
    calories: 350,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-22',
    updatedAt: '2024-03-25'
  },
  {
    id: '68',
    name: 'Oreo Shake',
    description: 'Cookies and cream milkshake',
    price: 15.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy', 'Gluten'],
    modifiers: ['Extra Oreo', 'Whipped Cream'],
    preparationTime: 6,
    calories: 380,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-03-23',
    updatedAt: '2024-03-26'
  },
  {
    id: '69',
    name: 'Toffee Shake',
    description: 'Sweet toffee flavored milkshake',
    price: 15.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Extra Toffee', 'Caramel'],
    preparationTime: 5,
    calories: 340,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-24',
    updatedAt: '2024-03-27'
  },
  {
    id: '70',
    name: 'Mango Shake',
    description: 'Tropical mango milkshake',
    price: 15.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Mango', 'Coconut'],
    preparationTime: 5,
    calories: 330,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-25',
    updatedAt: '2024-03-28'
  },
  {
    id: '71',
    name: 'Extra Ordinary Shake',
    description: 'A choice of 3 ice cream flavours',
    price: 20.00,
    category: 'Milkshakes',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 15,
    lowStockAlert: 3,
    allergens: ['Dairy'],
    modifiers: ['Vanilla', 'Chocolate', 'Strawberry'],
    preparationTime: 8,
    calories: 450,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-26',
    updatedAt: '2024-03-29'
  },
  // SMOOTHIES
  {
    id: '72',
    name: 'Avocado Delight',
    description: 'Avocado, spinach, dates and plain yoghurt',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Extra Avocado', 'Honey'],
    preparationTime: 6,
    calories: 280,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-27',
    updatedAt: '2024-03-30'
  },
  {
    id: '73',
    name: 'Banana Classic',
    description: 'Banana blended with vanilla yoghurt',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Banana', 'Honey'],
    preparationTime: 5,
    calories: 250,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-03-28',
    updatedAt: '2024-03-31'
  },
  {
    id: '74',
    name: 'Mango Madness',
    description: 'Fresh mangoes, pineapple, grapes, honey',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Mango', 'Extra Honey'],
    preparationTime: 6,
    calories: 220,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-29',
    updatedAt: '2024-04-01'
  },
  {
    id: '75',
    name: 'Blue Berry Classics',
    description: 'Blueberries, grapes, mangoes and coconut cream',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Blueberries', 'Coconut'],
    preparationTime: 6,
    calories: 240,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-30',
    updatedAt: '2024-04-02'
  },
  {
    id: '76',
    name: 'Straw Berry Classics',
    description: 'Fresh strawberries, mango, dates and passion juice',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Strawberries', 'Honey'],
    preparationTime: 6,
    calories: 210,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-03-31',
    updatedAt: '2024-04-03'
  },
  {
    id: '77',
    name: 'Sweet Dream',
    description: 'Banana, mango and vanilla yoghurt',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 22,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Extra Vanilla', 'Honey'],
    preparationTime: 5,
    calories: 260,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-04-01',
    updatedAt: '2024-04-04'
  },
  {
    id: '78',
    name: 'Green Pressure',
    description: 'Spinach, lemon, avocado and banana',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Spinach', 'Lemon'],
    preparationTime: 6,
    calories: 180,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-02',
    updatedAt: '2024-04-05'
  },
  {
    id: '79',
    name: 'Berry Blast',
    description: 'Blue berries, mango, apple and vanilla yoghurt',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Extra Berries', 'Apple'],
    preparationTime: 6,
    calories: 230,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-04-03',
    updatedAt: '2024-04-06'
  },
  {
    id: '80',
    name: 'Tropical Paradise',
    description: 'Mango, honey, coconut milk, banana and pineapple',
    price: 15.00,
    category: 'Smoothies',
    image: '/lovable-uploads/4c2a6f00-754f-4398-893a-158685bc2cce.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Coconut', 'Pineapple'],
    preparationTime: 6,
    calories: 250,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-04',
    updatedAt: '2024-04-07'
  },
  // HEALTHY FRESH JUICE
  {
    id: '81',
    name: 'Mango Juice',
    description: 'Sweet and creamy: Our mango juice bursts with tropical flavors',
    price: 10.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Ice', 'Mint'],
    preparationTime: 5,
    calories: 130,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-05',
    updatedAt: '2024-04-08'
  },
  {
    id: '82',
    name: 'Passion Fruit Juice',
    description: 'Tart and refreshing passion fruit juice rich in vitamins and anti-oxidants',
    price: 10.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Ice', 'Honey'],
    preparationTime: 5,
    calories: 95,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-06',
    updatedAt: '2024-04-09'
  },
  {
    id: '83',
    name: 'Carrot Juice',
    description: 'Freshly squeezed carrot juice rich in vitamins and minerals',
    price: 10.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 28,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Ginger', 'Ice'],
    preparationTime: 5,
    calories: 85,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-07',
    updatedAt: '2024-04-10'
  },
  {
    id: '84',
    name: 'Pineapple Juice',
    description: 'Juicy pineapple full of tropical flavor and health benefits',
    price: 10.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Ice', 'Mint'],
    preparationTime: 5,
    calories: 120,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-08',
    updatedAt: '2024-04-11'
  },
  {
    id: '85',
    name: 'Water Melon Juice',
    description: 'Refreshing water melon juice, hydrating and packed with vitamins',
    price: 10.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Ice', 'Lime'],
    preparationTime: 5,
    calories: 75,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-09',
    updatedAt: '2024-04-12'
  },
  {
    id: '86',
    name: 'Apple Juice',
    description: 'Crunchy and sweet; our apple juice is pressed from orchard apples',
    price: 15.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Ice', 'Cinnamon'],
    preparationTime: 5,
    calories: 110,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-10',
    updatedAt: '2024-04-13'
  },
  {
    id: '87',
    name: 'Orange Juice',
    description: '100% freshly squeezed: Our orange juice is bursting with citrus flavor and vitamin C',
    price: 15.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Ice', 'Pulp Free'],
    preparationTime: 5,
    calories: 105,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-11',
    updatedAt: '2024-04-14'
  },
  {
    id: '88',
    name: 'Lemon Juice',
    description: 'Tart and refreshing lemon juice aids digestion and boosts immunity',
    price: 15.00,
    category: 'Fresh Juice',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Honey', 'Ice'],
    preparationTime: 4,
    calories: 25,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-12',
    updatedAt: '2024-04-15'
  },
  // NOJOTOS & LEMONADES
  {
    id: '89',
    name: 'Virgin Mojito',
    description: 'Lime, lemon, sugar syrup, mint, ice cubes and sprite',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Mint', 'Extra Lime'],
    preparationTime: 6,
    calories: 120,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-13',
    updatedAt: '2024-04-16'
  },
  {
    id: '90',
    name: 'Blue Lagoon Nojito',
    description: 'Lemon juice, blue lagoon, sugar, mint and soda water',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Blue Lagoon', 'Mint'],
    preparationTime: 6,
    calories: 140,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-14',
    updatedAt: '2024-04-17'
  },
  {
    id: '91',
    name: 'Strawberry Moctail',
    description: 'Lime, strawberries, sugar, mint, oranges and sprite',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 22,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Strawberries', 'Mint'],
    preparationTime: 7,
    calories: 135,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-15',
    updatedAt: '2024-04-18'
  },
  {
    id: '92',
    name: 'Orange Mocktail',
    description: 'Lemon, orange juice, mint, sugar and sprite',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Orange', 'Mint'],
    preparationTime: 6,
    calories: 125,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-16',
    updatedAt: '2024-04-19'
  },
  {
    id: '93',
    name: 'Blueberry Mojito',
    description: 'Blueberries, lime, mint, lemon, sugar, ice cubes and sprite',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Blueberries', 'Mint'],
    preparationTime: 7,
    calories: 130,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-17',
    updatedAt: '2024-04-20'
  },
  {
    id: '94',
    name: 'Classic Lemonade',
    description: 'Lemon juice, sugar, syrup, water and ice cubes',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Extra Lemon', 'Mint'],
    preparationTime: 5,
    calories: 110,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-18',
    updatedAt: '2024-04-21'
  },
  {
    id: '95',
    name: 'Tropical Nojito',
    description: 'Blue curacao, sugar, lemon, orange and sparkling water',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Curacao', 'Orange'],
    preparationTime: 6,
    calories: 145,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-19',
    updatedAt: '2024-04-22'
  },
  {
    id: '96',
    name: 'Strawberry Lemonade',
    description: 'Strawberries, sugar, lemon and ice cubes',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 22,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Strawberries', 'Mint'],
    preparationTime: 6,
    calories: 115,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-20',
    updatedAt: '2024-04-23'
  },
  {
    id: '97',
    name: 'Mint Lemonade',
    description: 'Lemon, sugar, mint, orange, water, ice cubes',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Extra Mint', 'Orange'],
    preparationTime: 6,
    calories: 105,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-21',
    updatedAt: '2024-04-24'
  },
  {
    id: '98',
    name: 'Passion Paradise',
    description: 'Passion, lemon, lime, mint sugar syrup and sprite',
    price: 15.00,
    category: 'Lemonades',
    image: '/lovable-uploads/1793fc5b-eff0-44ed-9d25-2c5311776c62.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Passion', 'Mint'],
    preparationTime: 7,
    calories: 125,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-22',
    updatedAt: '2024-04-25'
  },
  // DETOX AND IMMUNE BOOSTERS
  {
    id: '99',
    name: 'Cucumber Cooler',
    description: 'Cucumber, spinach, lemon, apple and honey',
    price: 15.00,
    category: 'Detox Boosters',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Cucumber', 'Mint'],
    preparationTime: 6,
    calories: 65,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-23',
    updatedAt: '2024-04-26'
  },
  {
    id: '100',
    name: 'Frozen Mint',
    description: 'Pineapple, mint and orange blended together',
    price: 15.00,
    category: 'Detox Boosters',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Mint', 'Ice'],
    preparationTime: 6,
    calories: 85,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-24',
    updatedAt: '2024-04-27'
  },
  {
    id: '101',
    name: 'Morning Sunrise',
    description: 'Dates, grapes, lemon and honey',
    price: 15.00,
    category: 'Detox Boosters',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Honey', 'Ginger'],
    preparationTime: 6,
    calories: 95,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-25',
    updatedAt: '2024-04-28'
  },
  {
    id: '102',
    name: 'Clear Skin',
    description: 'Orange, carrot, ginger and honey',
    price: 15.00,
    category: 'Detox Boosters',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 22,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Ginger', 'Lemon'],
    preparationTime: 6,
    calories: 80,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-26',
    updatedAt: '2024-04-29'
  },
  {
    id: '103',
    name: 'Pineapple Classic',
    description: 'Pineapple, mint, cucumber and grapes',
    price: 15.00,
    category: 'Detox Boosters',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Pineapple', 'Mint'],
    preparationTime: 6,
    calories: 75,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-27',
    updatedAt: '2024-04-30'
  },
  {
    id: '104',
    name: 'Beets of Life',
    description: 'Beetroot, dates and orange juice',
    price: 15.00,
    category: 'Detox Boosters',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Beetroot', 'Ginger'],
    preparationTime: 6,
    calories: 90,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-28',
    updatedAt: '2024-05-01'
  },
  // METRIC REMEDIES
  {
    id: '105',
    name: 'Morning After',
    description: 'A revitalizing drink made with coconut milk, pineapple juice and a splash of ginger shot',
    price: 20.00,
    category: 'Metric Remedies',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 15,
    lowStockAlert: 3,
    allergens: [],
    modifiers: ['Extra Ginger', 'Coconut'],
    preparationTime: 7,
    calories: 120,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-29',
    updatedAt: '2024-05-02'
  },
  {
    id: '106',
    name: 'Recovery Smoothie',
    description: 'A blend of banana, spinach, almond milk and honey',
    price: 20.00,
    category: 'Metric Remedies',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: ['Nuts'],
    modifiers: ['Extra Banana', 'Honey'],
    preparationTime: 6,
    calories: 180,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-04-30',
    updatedAt: '2024-05-03'
  },
  {
    id: '107',
    name: 'Hangover Recovery',
    description: 'A soothing blend of green tea, peppermint and lemon',
    price: 20.00,
    category: 'Metric Remedies',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 15,
    lowStockAlert: 3,
    allergens: [],
    modifiers: ['Extra Lemon', 'Honey'],
    preparationTime: 8,
    calories: 25,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-05-01',
    updatedAt: '2024-05-04'
  },
  // KIDS CORNER
  {
    id: '108',
    name: 'Kids Mango Juice',
    description: 'Sweet mango juice perfect for kids',
    price: 6.00,
    category: 'Kids Corner',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 35,
    lowStockAlert: 7,
    allergens: [],
    modifiers: ['Less Sweet', 'Ice'],
    preparationTime: 4,
    calories: 90,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-05-02',
    updatedAt: '2024-05-05'
  },
  {
    id: '109',
    name: 'Kids Passion Juice',
    description: 'Mild passion fruit juice for children',
    price: 6.00,
    category: 'Kids Corner',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Less Sweet', 'Diluted'],
    preparationTime: 4,
    calories: 70,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-05-03',
    updatedAt: '2024-05-06'
  },
  {
    id: '110',
    name: 'Kids Orange Juice',
    description: 'Fresh orange juice for kids',
    price: 6.00,
    category: 'Kids Corner',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 32,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Pulp Free', 'Less Sweet'],
    preparationTime: 4,
    calories: 80,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-05-04',
    updatedAt: '2024-05-07'
  },
  {
    id: '111',
    name: 'Kids Water Melon Juice',
    description: 'Refreshing watermelon juice for children',
    price: 6.00,
    category: 'Kids Corner',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: [],
    modifiers: ['Ice', 'Less Sweet'],
    preparationTime: 4,
    calories: 60,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-05-05',
    updatedAt: '2024-05-08'
  },
  {
    id: '112',
    name: 'Kids Beetroot Juice',
    description: 'Nutritious beetroot juice for kids',
    price: 6.00,
    category: 'Kids Corner',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: [],
    modifiers: ['Honey', 'Diluted'],
    preparationTime: 5,
    calories: 65,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-05-06',
    updatedAt: '2024-05-09'
  },
  {
    id: '113',
    name: 'Kids Mocktail',
    description: 'Fun colorful non-alcoholic drink for children',
    price: 10.00,
    category: 'Kids Corner',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: [],
    modifiers: ['Extra Colorful', 'Fun Garnish'],
    preparationTime: 6,
    calories: 95,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: '2024-05-07',
    updatedAt: '2024-05-10'
  },
  // KIDS SMOOTHIES
  {
    id: '114',
    name: 'Queens Best',
    description: 'Mango blended with vanilla yoghurt',
    price: 9.00,
    category: 'Kids Smoothies',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Mango', 'Less Sweet'],
    preparationTime: 5,
    calories: 150,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-08',
    updatedAt: '2024-05-11'
  },
  {
    id: '115',
    name: 'Berry Blast Kids',
    description: 'Blue berries, mango apple and vanilla yoghurt',
    price: 9.00,
    category: 'Kids Smoothies',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Extra Berries', 'Apple Pieces'],
    preparationTime: 6,
    calories: 140,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-09',
    updatedAt: '2024-05-12'
  },
  {
    id: '116',
    name: 'Banana Special Kids',
    description: 'Fresh banana blended with vanilla yoghurt',
    price: 9.00,
    category: 'Kids Smoothies',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Banana', 'Honey'],
    preparationTime: 5,
    calories: 160,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-10',
    updatedAt: '2024-05-13'
  },
  {
    id: '117',
    name: 'Princess Moana',
    description: 'Strawberry, mango and vanilla yoghurt',
    price: 15.00,
    category: 'Kids Smoothies',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 18,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Extra Strawberry', 'Fun Garnish'],
    preparationTime: 6,
    calories: 170,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-11',
    updatedAt: '2024-05-14'
  },
  // KIDS MILKSHAKES
  {
    id: '118',
    name: 'Kids Vanilla Shake',
    description: 'Mild vanilla milkshake for children',
    price: 9.00,
    category: 'Kids Milkshakes',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 30,
    lowStockAlert: 6,
    allergens: ['Dairy'],
    modifiers: ['Less Sweet', 'Fun Straw'],
    preparationTime: 5,
    calories: 180,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-12',
    updatedAt: '2024-05-15'
  },
  {
    id: '119',
    name: 'Kids Strawberry Shake',
    description: 'Sweet strawberry milkshake for kids',
    price: 9.00,
    category: 'Kids Milkshakes',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Extra Strawberry', 'Whipped Cream'],
    preparationTime: 5,
    calories: 190,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-13',
    updatedAt: '2024-05-16'
  },
  {
    id: '120',
    name: 'Kids Chocolate Shake',
    description: 'Mild chocolate milkshake for children',
    price: 9.00,
    category: 'Kids Milkshakes',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 25,
    lowStockAlert: 5,
    allergens: ['Dairy'],
    modifiers: ['Less Chocolate', 'Fun Garnish'],
    preparationTime: 5,
    calories: 200,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-14',
    updatedAt: '2024-05-17'
  },
  {
    id: '121',
    name: 'Kids Oreo Shake',
    description: 'Mild cookies and cream shake for kids',
    price: 9.00,
    category: 'Kids Milkshakes',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy', 'Gluten'],
    modifiers: ['Less Cookie', 'Fun Topping'],
    preparationTime: 6,
    calories: 210,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: '2024-05-15',
    updatedAt: '2024-05-18'
  },
  {
    id: '122',
    name: 'Kids Caramel Shake',
    description: 'Sweet caramel milkshake for children',
    price: 9.00,
    category: 'Kids Milkshakes',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 20,
    lowStockAlert: 4,
    allergens: ['Dairy'],
    modifiers: ['Less Caramel', 'Whipped Cream'],
    preparationTime: 5,
    calories: 195,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-16',
    updatedAt: '2024-05-19'
  },
  // ICE CREAM SCOOPS
  {
    id: '123',
    name: 'Ice Cream Scoops',
    description: 'Vanilla, Strawberry, Chocolate - Ice Cream flavours of your choice',
    price: 6.00,
    category: 'Ice Cream',
    image: '/lovable-uploads/33726c50-7cf1-4db6-8f01-a00304e6d76b.png',
    isAvailable: true,
    stockCount: 40,
    lowStockAlert: 8,
    allergens: ['Dairy'],
    modifiers: ['Vanilla', 'Strawberry', 'Chocolate'],
    preparationTime: 3,
    calories: 150,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: '2024-05-17',
    updatedAt: '2024-05-20'
  }
];

const categories = ['All', 'Hot Starters', 'Main Course', 'Pizza', 'Chicken', 'Beef', 'Fish', 'Indian', 'Goat', 'Burgers', 'Pasta', 'Desserts', 'Coffee', 'Iced Coffee', 'Chocolate', 'Tea', 'Organic Chai', 'Flavored Tea', 'Milkshakes', 'Smoothies', 'Fresh Juice', 'Lemonades', 'Detox Boosters', 'Metric Remedies', 'Kids Corner', 'Kids Smoothies', 'Kids Milkshakes', 'Ice Cream'];

export default function Items() {
  const [items, setItems] = useState<Item[]>(initialItems);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<Item | null>(null);
  const [viewMode, setViewMode] = useState<'grid' | 'table'>('grid');
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    price: 0,
    category: 'Hot Starters',
    image: '',
    stockCount: 0,
    lowStockAlert: 5,
    allergens: [] as string[],
    modifiers: [] as string[],
    preparationTime: 5,
    calories: 0,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false
  });
  const { toast } = useToast();

  const filteredItems = items.filter(item => {
    const matchesSearch = item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         item.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = selectedCategory === 'All' || item.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const handleSave = () => {
    if (!formData.name.trim()) {
      toast({
        title: "Validation Error",
        description: "Item name is required",
        variant: "destructive"
      });
      return;
    }

    if (formData.price <= 0) {
      toast({
        title: "Validation Error",
        description: "Price must be greater than 0",
        variant: "destructive"
      });
      return;
    }

    if (editingItem) {
      setItems(prev => prev.map(item => 
        item.id === editingItem.id 
          ? { 
              ...item, 
              ...formData,
              isAvailable: formData.stockCount > 0,
              updatedAt: new Date().toISOString().split('T')[0] 
            }
          : item
      ));
      toast({
        title: "Item Updated",
        description: `${formData.name} has been updated successfully`
      });
    } else {
      const newItem: Item = {
        id: Date.now().toString(),
        ...formData,
        isAvailable: formData.stockCount > 0,
        createdAt: new Date().toISOString().split('T')[0],
        updatedAt: new Date().toISOString().split('T')[0]
      };
      setItems(prev => [...prev, newItem]);
      toast({
        title: "Item Created",
        description: `${formData.name} has been created successfully`
      });
    }

    handleCloseDialog();
  };

  const handleEdit = (item: Item) => {
    setEditingItem(item);
    setFormData({
      name: item.name,
      description: item.description,
      price: item.price,
      category: item.category,
      image: item.image,
      stockCount: item.stockCount,
      lowStockAlert: item.lowStockAlert,
      allergens: item.allergens,
      modifiers: item.modifiers,
      preparationTime: item.preparationTime,
      calories: item.calories,
      isVegetarian: item.isVegetarian,
      isVegan: item.isVegan,
      isGlutenFree: item.isGlutenFree
    });
    setIsDialogOpen(true);
  };

  const handleDelete = (id: string) => {
    setItems(prev => prev.filter(item => item.id !== id));
    toast({
      title: "Item Deleted",
      description: "Item has been deleted successfully"
    });
  };

  const toggleAvailability = (id: string) => {
    setItems(prev => prev.map(item =>
      item.id === id ? { ...item, isAvailable: !item.isAvailable } : item
    ));
  };

  const handleCloseDialog = () => {
    setIsDialogOpen(false);
    setEditingItem(null);
    setFormData({
      name: '',
      description: '',
      price: 0,
      category: 'Hot Starters',
      image: '',
      stockCount: 0,
      lowStockAlert: 5,
      allergens: [],
      modifiers: [],
      preparationTime: 5,
      calories: 0,
      isVegetarian: false,
      isVegan: false,
      isGlutenFree: false
    });
  };

  const handleAddItem = () => {
    setEditingItem(null);
    setIsDialogOpen(true);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 p-6">
      <div className="max-w-7xl mx-auto">
        <ItemsHeader />
        
        <ItemsControls
          searchTerm={searchTerm}
          setSearchTerm={setSearchTerm}
          selectedCategory={selectedCategory}
          setSelectedCategory={setSelectedCategory}
          categories={categories}
          viewMode={viewMode}
          setViewMode={setViewMode}
          onAddItem={handleAddItem}
        />

        <ItemStats items={items} />

        <ItemsDisplay
          viewMode={viewMode}
          filteredItems={filteredItems}
          onEdit={handleEdit}
          onDelete={handleDelete}
          onToggleAvailability={toggleAvailability}
          searchTerm={searchTerm}
          selectedCategory={selectedCategory}
        />

        <ItemForm
          isOpen={isDialogOpen}
          onClose={handleCloseDialog}
          editingItem={editingItem}
          formData={formData}
          setFormData={setFormData}
          onSave={handleSave}
          categories={categories}
        />
      </div>
    </div>
  );
}
