// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmpqqorbdobrjoytwmck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtcHFxb3JiZG9icmpveXR3bWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQ0NjUsImV4cCI6MjA2NTUxMDQ2NX0.ebPGsKnJinSM8f2bWGf1NXMP_5YpcvotCkGsyc3bJrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);